# Generated by Django 5.0.6 on 2024-06-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_endereco_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField(default=0)),
                ('cor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=255)),
                ('referencia', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
