# Generated by Django 5.0.6 on 2024-06-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_itemvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='parcelas_pgto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_pgto',
            field=models.IntegerField(choices=[(1, 'A vista'), (2, 'Parcelado')], default=1),
        ),
    ]
