# Generated by Django 5.0.6 on 2024-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_remove_itemvenda_comissao_venda_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='valor_unitario_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
