# Generated by Django 5.0.6 on 2024-07-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_itemvenda_valor_unitario_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvenda',
            old_name='valor_unitario_venda',
            new_name='preco_unitario_venda',
        ),
    ]
