# Generated by Django 5.0.6 on 2024-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_slug',
            field=models.CharField(default='', max_length=64),
        ),
    ]
