# Generated by Django 5.0.6 on 2024-07-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_product_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_slug',
            field=models.SlugField(default='', max_length=64),
        ),
    ]
